<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LocationSeeder extends Seeder
{
    public function run()
    {
        DB::table('location')->insert([
            [
                'id_location' => 1,
                'nama_lokasi' => 'EV Hub Stasiun Tugu Yogyakarta',
                'alamat' => 'Jl. Ps. Kembang, Sosromenduran, Gedong Tengen, Yogyakarta',
                'latitude' => -7.785278,
                'longitude' => 110.362222,
                'jam_buka' => '06:00:00',
                'jam_tutup' => '22:00:00',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 2,
                'nama_lokasi' => 'EV Hub Plaza Ambarrukmo',
                'alamat' => 'Jl. Laksda Adisucipto KM. 6, Depok, Sleman, Yogyakarta',
                'latitude' => -7.782800,
                'longitude' => 110.401200,
                'jam_buka' => '10:00:00',
                'jam_tutup' => '22:00:00',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 3,
                'nama_lokasi' => 'EV Hub Malioboro Mall',
                'alamat' => 'Jl. Malioboro No.52-58, Suryatmajan, Danurejan, Yogyakarta',
                'latitude' => -7.792650,
                'longitude' => 110.365850,
                'jam_buka' => '10:00:00',
                'jam_tutup' => '22:00:00',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 4,
                'nama_lokasi' => 'EV Hub Pakuwon Mall Jogja',
                'alamat' => 'Jl. Ring Road Utara, Condongcatur, Depok, Sleman, Yogyakarta',
                'latitude' => -7.758400,
                'longitude' => 110.398100,
                'jam_buka' => '10:00:00',
                'jam_tutup' => '22:00:00',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 5,
                'nama_lokasi' => 'EV Hub Galeria Mall',
                'alamat' => 'Jl. Jend. Sudirman No.99-101, Terban, Gondokusuman, Yogyakarta',
                'latitude' => -7.783100,
                'longitude' => 110.375400,
                'jam_buka' => '10:00:00',
                'jam_tutup' => '22:00:00',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 6,
                'nama_lokasi' => 'EV Hub Kantor PLN UP3 Yogyakarta',
                'alamat' => 'Jl. Laksda Adisucipto No.58, Demangan, Gondokusuman, Yogyakarta',
                'latitude' => -7.784500,
                'longitude' => 110.388900,
                'jam_buka' => '00:00:00',
                'jam_tutup' => '23:59:59',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 7,
                'nama_lokasi' => 'EV Hub Sleman City Hall',
                'alamat' => 'Jl. Magelang KM. 9, Denggung, Tridadi, Sleman, Yogyakarta',
                'latitude' => -7.719200,
                'longitude' => 110.362500,
                'jam_buka' => '10:00:00',
                'jam_tutup' => '22:00:00',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 8,
                'nama_lokasi' => 'EV Hub Jogja City Mall',
                'alamat' => 'Jl. Magelang KM. 6 No.18, Sinduadi, Mlati, Sleman, Yogyakarta',
                'latitude' => -7.747500,
                'longitude' => 110.363400,
                'jam_buka' => '10:00:00',
                'jam_tutup' => '22:00:00',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 9,
                'nama_lokasi' => 'EV Hub Bandara Internasional Adisutjipto',
                'alamat' => 'Jl. Raya Solo KM. 9, Maguwoharjo, Depok, Sleman, Yogyakarta',
                'latitude' => -7.787100,
                'longitude' => 110.431200,
                'jam_buka' => '06:00:00',
                'jam_tutup' => '21:00:00',
                'status' => 'Maintenance',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_location' => 10,
                'nama_lokasi' => 'EV Hub XT Square Yogyakarta',
                'alamat' => 'Jl. Veteran No.150-151, Pandeyan, Umbulharjo, Yogyakarta',
                'latitude' => -7.814300,
                'longitude' => 110.384500,
                'jam_buka' => '08:00:00',
                'jam_tutup' => '22:00:00',
                'status' => 'Aktif',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}